### ISSUE TITLE
How to change "FILTER MENU" text on top of the card?

### ISSUE THREAD

**Issue by phoenixg** [nrml-co/nova-big-filter#2]

**Comment by edanisko** [comment]
Good idea.  I’ll add something that lets you do that. I’m thinking something like:

BigFilter()->setTitle(“your title”)

I’ll add it tonight at some point. 

Thanks
Ed

**Comment by phoenixg** [comment]
@edanisko Do you have time to update that? I'm looking forward to.

**Comment by edanisko** [comment]
@phoenixg done.

**Comment by phoenixg** [comment]
@edanisko Great job!
