### ISSUE TITLE
Save filters after reloading page

### ISSUE THREAD

**Issue by oleg-vysotsky** [nrml-co/nova-big-filter#6]
Filter should save events_filter to url otherwise we will lost all the filters after page reloading .

http://nova.lamoore.local/resources/events?events_page=1&events_filter=W3siY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXEV2ZW50U3RhcnREYXRlIiwidmFsdWUiOiIifSx7ImNsYXNzIjoiQXBwXFxOb3ZhXFxGaWx0ZXJzXFxFdmVudEVuZERhdGUiLCJ2YWx1ZSI6IiJ9LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXEV2ZW50QnlQdWJsaWMiLCJ2YWx1ZSI6IjAifSx7ImNsYXNzIjoiQXBwXFxOb3ZhXFxGaWx0ZXJzXFxFdmVudEJ5VHlwZSIsInZhbHVlIjoiIn0seyJjbGFzcyI6IkFwcFxcTm92YVxcRmlsdGVyc1xcRXZlbnRCeVBvc3RjYXJkIiwidmFsdWUiOiIifSx7ImNsYXNzIjoiQXBwXFxOb3ZhXFxGaWx0ZXJzXFxFdmVudEJ5UG9zdGNhcmRUeXBlIiwidmFsdWUiOiIifSx7ImNsYXNzIjoiQXBwXFxOb3ZhXFxGaWx0ZXJzXFxFdmVudEJ5UmF0aW5nIiwidmFsdWUiOiIifV0%3D

We check it on Nova 2.0.1 and Nova 2.0.5.

**Comment by edanisko** [comment]
Sorry for delay.  Good call. I will work on this and update.

**Comment by vigneshVic** [comment]
> Sorry for delay. Good call. I will work on this and update.

Are u completed?
Also how to update this package?

**Comment by LorenzoSapora** [comment]
Bump. I wasn't even aware this wasn't a thing until I reloaded the page.

**Comment by edanisko** [comment]
fixed
